[package]
name = "companies_house"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
base64 = "0.22.1"
reqwest = { version = "0.12.4", features = ["blocking","json"] }
serde = "1.0.203"
serde_json = "1.0.117"
